import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
import KeyDisplay from '@/components/KeyDisplay'
import Progressions from '@/components/Progressions'
import { Key } from 'tonal'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [keys] = useState([
    ['C', 'major'],
    ['A', 'minor'],
    ['G', 'major'],
    ['E', 'minor'],
    ['D', 'major'],
    ['B', 'minor'],
    ['A', 'major'],
    ['F#', 'minor'],
    ['E', 'major'],
    ['C#', 'minor'],
    ['B', 'major'],
    ['G#', 'minor'],
    ['F#', 'major'],
    ['D#', 'minor'],
    ['C#', 'major'],
    ['A#', 'minor'],
    ['F', 'major'],
    ['D', 'minor'],
    ['Bb', 'major'],
    ['G', 'minor'],
    ['Eb', 'major'],
    ['C', 'minor'],
    ['Ab', 'major'],
    ['F', 'minor'],
    ['Db', 'major'],
    ['Bb', 'minor'],
    ['Gb', 'major'],
    ['Eb', 'minor'],
    ['Cb', 'major'],
    ['Ab', 'minor']
  ])
  const [randomKey, setRandomKey] = useState()
  const [tempo, setTempo] = useState()

  useEffect(() => {
    generateKey(keys)
    generateTempo()
  }, [])

  const generateKey = (keys) => {
    let generatedKey = keys[Math.floor(Math.random() * keys.length)]
    if (generatedKey[1] == 'major') {
      setRandomKey(Key.majorKey(generatedKey[0]))
    } else {
      setRandomKey(Key.minorKey(generatedKey[0]))
    }
  }

  const generateTempo = () => {
    setTempo(Math.floor(Math.random() * (180 - 60) + 60))
  }
  const handleClick = (e) => {
    e.preventDefault()
    generateKey(keys)
    generateTempo()
  }

  return (
    <>
      <Head>
        <title>Write A Song Today</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Lets Write A Song</h1>
        <KeyDisplay randomKey={randomKey} />
        <div className={styles['.tempo-wrapper']}>
          <div className={styles.tempo}>
            <p>Tempo</p>
            <h2>{tempo}</h2>
          </div>
        </div>
        <Progressions randomKey={randomKey} />
        <button
          className={styles['generate-button']}
          type="button"
          onClick={handleClick}
        >
          Get Inspired
        </button>
      </main>
    </>
  )
}
