import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
import KeyDisplay from '@/components/KeyDisplay'
import Progressions from '@/components/Progressions'
import { Key } from 'tonal'

import About from '@/components/About'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [keys] = useState([
    ['C', 'major'],
    ['A', 'minor'],
    ['G', 'major'],
    ['E', 'minor'],
    ['D', 'major'],
    ['B', 'minor'],
    ['A', 'major'],
    ['F#', 'minor'],
    ['E', 'major'],
    ['C#', 'minor'],
    ['B', 'major'],
    ['G#', 'minor'],
    ['F#', 'major'],
    ['D#', 'minor'],
    ['C#', 'major'],
    ['A#', 'minor'],
    ['F', 'major'],
    ['D', 'minor'],
    ['Bb', 'major'],
    ['G', 'minor'],
    ['Eb', 'major'],
    ['C', 'minor'],
    ['Ab', 'major'],
    ['F', 'minor'],
    ['Db', 'major'],
    ['Bb', 'minor'],
    ['Gb', 'major'],
    ['Eb', 'minor'],
    ['Cb', 'major'],
    ['Ab', 'minor']
  ])
  const [randomKey, setRandomKey] = useState()
  const [tempo, setTempo] = useState()

  useEffect(() => {
    generateKey(keys)
    generateTempo()
  }, [keys])

  const generateKey = (keys) => {
    let generatedKey = keys[Math.floor(Math.random() * keys.length)]
    if (generatedKey[1] == 'major') {
      setRandomKey(Key.majorKey(generatedKey[0]))
    } else {
      setRandomKey(Key.minorKey(generatedKey[0]))
    }
  }

  const generateTempo = () => {
    setTempo(Math.floor(Math.random() * (180 - 60) + 60))
  }
  const handleClick = (e) => {
    e.preventDefault()
    generateKey(keys)
    generateTempo()
  }

  return (
    <>
      <Head>
        <title>Write A Song Today</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:title" content="WriteASong.Today" />
        <meta property="og:description" content="A fun songwriting tool" />
        <meta
          property="og:image"
          content="https://res.cloudinary.com/silverbeard/image/upload/v1675984256/Portfolio/project%20pictures/Screen_Shot_2023-02-09_at_6.10_gy6jkm.png"
        />
        <meta property="og:url" content="https://staging.writeasong.today" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <main className={styles.main}>
        <header className="header">
          <h1>Let&apos;s WriteASong.Today</h1>
        </header>
        <div className={styles['page-wrapper']}>
          <div className="content">
            <div style={{ textAlign: 'center' }}>
              <KeyDisplay randomKey={randomKey} />
              <button
                className="generate-button random"
                onClick={() => generateKey(keys)}
              >
                Randomize
              </button>
            </div>
            <Progressions randomKey={randomKey} />
            <div style={{ textAlign: 'center' }}>
              <div className="card">
                <p>Tempo</p>
                <div className="tempo">
                  <h2>{tempo}</h2>
                  <p>BPM</p>
                </div>
              </div>
              <button
                className="generate-button random"
                onClick={() => generateTempo()}
              >
                Randomize
              </button>
            </div>
          </div>
          <button
            className="generate-button"
            type="button"
            onClick={handleClick}
          >
            Get Inspired
          </button>
          <About />
        </div>
      </main>
      <footer>&copy; Frank Marra 2023</footer>
    </>
  )
}
